services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: flask-api
    ports:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: react-client
    ports:
      - "3000:80"
